### ISSUE TITLE
Document CBET (old RITlug) Servers

### ISSUE THREAD

**Issue by axk4545** [RITlug/runbook#47]
We need to document how to access the RITlug servers to avoid a repeat of the situation the last 3 years where we knew they existed but had no idea who to contact. We need to ensure we have a way to contact the team that manages the datacenter, the sysadmin team for the Center for Bioscience Education and Technology (Bldg 75)
Rochester Institute of Technology

**Comment by ct-martin** [comment]
Blocking this on RITlug/infrastructure#14

**Comment by Tjzabel** [comment]
These servers are gone. Closing.
