### ISSUE TITLE
Document President Role

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/runbook#50]

**Comment by jwflory** [comment]
Thanks for filing these to help track them.

---

_Related to RITlug/tasks#8._

**Comment by jwflory** [comment]
_Discussed in 2018-08-31 eboard meeting._

---

@Tjzabel will take initiative to write a first draft for the Runbook page on the President role by our next eboard meeting on Monday, September 10th. We can review it before the meeting and have any follow-up discussion, if necessary, in our meeting time.
