### ISSUE TITLE
Update Website Documentation

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/runbook#52]
The website [site source](http://runbook.ritlug.com/en/latest/infrastructure/website.html#site-source) is very out of date, and with the new website redesign, now would be a good idea to update this page.

**Comment by ct-martin** [comment]
Note to self: section on updating meeting location/time

**Comment by jwflory** [comment]
This is the last remaining issue for RITlug/tasks#8. Since its motivation was to make the Runbook relevant again, we're closing that issue and moving further discussion on the site here.

**Comment by ct-martin** [comment]
Note to self: at this point I should essentially go through all of the site's code (!= content) line-by-line for this issue

**Comment by jrtechs** [comment]
I'm updating this ticket to mention that we should document how we upload talks slides to the website.
