### ISSUE TITLE
Add new page for eboard meetings

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/runbook#64]
### Problem
There is no documentation on how we run our eboard meetings, or the process on how we prepare for each week's meeting.

### Solution
Create a new page under Events documenting the eboard meeting process. This page should include: 

- Assigning "review at meeting" label to issues
- Allocating eboard meeting room each semester
- General layout of meetings
- End-of-meeting tasks

**Comment by jrtechs** [comment]
# Eboard Meeting Notes 9-17-18

@icflournoy is going to take a stab at this page.

## Action Items

@icflournoy follow up next eboard meeting 9-24 with a draft.

**Comment by icflournoy** [comment]
Picking this up now, will have a draft by today's meeting.

**Comment by icflournoy** [comment]
### 2018-09-24 Eboard Meeting

Assigning @jwflory @Tjzabel @jrtechs to review.

@icflournoy needs to add:
- left to right note
- for remote viewers, share screen

**Comment by jwflory** [comment]
@icflournoy Think you can finish this one this week?
