### ISSUE TITLE
Document CampusGroups design approval process

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/runbook#77]
We should document what the process is on getting a design approved through https://campusgroups.rit.edu/clubs.

**Comment by nlMeminger** [comment]
Ideally this would then live in the run book

**Comment by Tjzabel** [comment]
@nlMeminger where do you think this issue was filed against :smile:

**Comment by nlMeminger** [comment]
Look now, don’t go expecting me to read the entire subject line of every
GitHub email I get. Ain’t nobody got time for that.

**Comment by Tjzabel** [comment]
This rarely needs to happen and I doubt anyone will get around to this.
